version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: ecommerce-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  # Backend API server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ecommerce-server
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://admin:password123@mongodb:27017/ecommerce?authSource=admin
      PORT: 5000
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      NODE_ENV: production
      CLIENT_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - ecommerce-network
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend Next.js application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000/api
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_your_stripe_key_here
    container_name: ecommerce-client
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_your_stripe_key_here
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongodb_data: