apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ecommerce
type: Opaque
data:
  password: cGFzc3dvcmQxMjM= # base64 encoded "password123"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGItc2VydmljZToyNzAxNy9lY29tbWVyY2U/YXV0aFNvdXJjZT1hZG1pbg== # base64 encoded MongoDB URI
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u # base64 encoded JWT secret
  stripe-publishable-key: cGtfdGVzdF95b3VyX3N0cmlwZV9rZXlfaGVyZQ== # base64 encoded Stripe key