apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-server
  namespace: ecommerce
  labels:
    app: ecommerce-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-server
  template:
    metadata:
      labels:
        app: ecommerce-server
    spec:
      containers:
      - name: server
        image: ecommerce-server:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5001"
        - name: CLIENT_URL
          value: "http://localhost:3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-server-service
  namespace: ecommerce
  labels:
    app: ecommerce-server
spec:
  selector:
    app: ecommerce-server
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP